apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: default
  annotations:
    # Label selector for pods/deployments to restart when this ConfigMap changes
    k8spatterns.io/restart-on-change: "app=config-demo"
data:
  message: "Hello, students!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
  labels:
    app: config-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-demo
  template:
    metadata:
      labels:
        app: config-demo
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/nginx:1.25-alpine
          ports:
            - containerPort: 80
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: message
          volumeMounts:
            - name: cfg
              mountPath: /usr/share/nginx/html
      volumes:
        - name: cfg
          configMap:
            name: demo-config
            items:
              - key: message
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
  labels:
    app: config-demo
spec:
  selector:
    app: config-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
