apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  labels:
    app: nginx
    type: job
spec:
  template:
    metadata:
      labels:
        app: nginx
        type: job
    spec:
      containers:
      - name: nginx-job
        image: nginx:1.25
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Starting nginx job..."
            nginx -g "daemon off;" &
            sleep 30
            echo "Job completed successfully"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      restartPolicy: Never
  backoffLimit: 4
