apiVersion: v1
kind: Namespace
metadata:
  name: nginx-namespace
  labels:
    name: nginx-namespace
    environment: development
  annotations:
    description: "Namespace for nginx applications"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-quota
  namespace: nginx-namespace
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "10"
    services: "5"
