apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: random-generator-log
  labels:
    app: random-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
