apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-deployments
  namespace: default
subjects:
- kind: User
  name: devops-user
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: deployment-manager-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
