apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    app: nginx
type: Opaque
data:
  # echo -n 'admin' | base64
  username: YWRtaW4=
  # echo -n 'password123' | base64
  password: cGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls
  labels:
    app: nginx
type: kubernetes.io/tls
stringData:
  # Example self-signed certificate and key (for demonstration only)
  # In production, use proper certificates from a CA
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICljCCAX4CCQCKOtLUmAD8BDANBgkqhkiG9w0BAQsFADANMQswCQYDVQQGEwJV
    UzAeFw0yNDA0MjMxMjAwMDBaFw0yNTA0MjMxMjAwMDBaMA0xCzAJBgNVBAYTAlVT
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuVMeRHjQnWngsli0+bWT
    nkQHSlqazQ4QQABJRefOf7/t48S4ShhBdqVoOwdqQQQwAbTHOEABCDEFGHIJKLMN
    OPQRSTUVWXYZabABCDEFGHIJKLMNOPQRSTUVWXYZabABCDEFGHIJKLMNOPQRSTUV
    WXYZabABCDEFGHIJKLMNOPQRSTUVWXYZabABCDEFGHIJKLMNOPQRSTUVWXYZabAB
    CDEFGHIJKLMNOPQRSTUVWXYZ
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5Ux5EeNCdaeCy
    WLT5tZOeRAdKWprNDhBAAElF5859v+3jxLhKGEF2pWg7B2pBBDABtMc4QAEIMQUY
    cgkosw049BFJNRVZdhlpsAEIMQUYcgkosw049BFJNRVZdhlpsAEIMQUYcgkosw04
    9BFJNRVZdhlpsAEIMQUYcgkosw049BFJNRVZdhlpsAEIMQUYcgkosw049BFJNRVZ
    dhlpsAECAwEAAQKCAQBm8B5UrF5kGqUTvHRTdHBGl7/OGE0q5x5x5x5x5x5x5x5x
    5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x
    5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x
    5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x
    5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x5x
    -----END PRIVATE KEY-----
