apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-test-client
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: helm-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/argo/manifests/test-clients
    repoURL: https://github.com/voatsap/k8s-pine/
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
