apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-examples
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/argo
    repoURL: https://github.com/voatsap/k8s-pine/
    targetRevision: main
    directory:
      include: "helm-*.yaml"
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
