apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/controller/controller
    repoURL: https://github.com/voatsap/k8s-pine/
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
