# HashiCorp Vault deployment with persistent storage
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: default
  labels:
    app: vault
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    storage "file" {
      path = "/vault/data"
    }
    
    api_addr = "http://127.0.0.1:8200"
    cluster_addr = "http://127.0.0.1:8201"
    
    # Disable mlock for development
    disable_mlock = true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-storage
  namespace: default
  labels:
    app: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
        - name: vault
          image: hashicorp/vault:1.15
          ports:
            - containerPort: 8200
              name: vault-port
              protocol: TCP
            - containerPort: 8201
              name: cluster-port
              protocol: TCP
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_CONFIG_DIR
              value: "/vault/config"
          command:
            - "/bin/sh"
            - "-c"
            - |
              vault server -config=/vault/config/vault.hcl
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
            - name: vault-storage
              mountPath: /vault/data
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-storage
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: vault-port
      port: 8200
      targetPort: 8200
      protocol: TCP
  type: ClusterIP
