apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cleanupjobs.k8spatterns.io
spec:
  group: k8spatterns.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceType:
                type: string
                description: "Type of resource to clean up (e.g., 'configmap', 'secret')"
              selector:
                type: string
                description: "Label selector for resources to clean up"
              cleanupCommand:
                type: string
                description: "Custom cleanup command to execute"
            required:
            - resourceType
            - selector
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Cleaning", "Completed", "Failed"]
              message:
                type: string
              lastUpdate:
                type: string
                format: date-time
        required:
        - spec
  scope: Namespaced
  names:
    plural: cleanupjobs
    singular: cleanupjob
    kind: CleanupJob
    shortNames:
    - cj
