apiVersion: v1
kind: Pod
metadata:
  name: database-primary
  labels:
    app: database-primary
    tier: database
    role: primary
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "appdb"
    - name: POSTGRES_USER
      value: "appuser"
    - name: POSTGRES_PASSWORD
      value: "password123"
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1Gi"
        cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  labels:
    app: api-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
        tier: backend
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - database-primary
                - key: tier
                  operator: In
                  values:
                  - database
              topologyKey: kubernetes.io/hostname
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - cache
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: api-server
        image: node:18-alpine
        command: ["node", "-e", "console.log('API Server running...'); setInterval(() => {}, 1000);"]
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "database-primary"
        - name: DB_PORT
          value: "5432"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
