apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexible-app-preferred
  labels:
    app: flexible-app-preferred
spec:
  replicas: 6
  selector:
    matchLabels:
      app: flexible-app-preferred
  template:
    metadata:
      labels:
        app: flexible-app-preferred
        tier: application
    spec:
      # Preferred scheduling constraints - scheduler will try to satisfy these but can ignore if needed
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - compute-optimized
          - weight: 60
            preference:
              matchExpressions:
              - key: zone
                operator: In
                values:
                - us-central1-a
                - us-central1-b
          - weight: 40
            preference:
              matchExpressions:
              - key: instance-type
                operator: In
                values:
                - n1-standard-4
                - n1-standard-8
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - cache
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flexible-app-preferred
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: flexible-app-preferred
      containers:
      - name: web-service
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-preferred
  labels:
    app: analytics-preferred
spec:
  replicas: 4
  selector:
    matchLabels:
      app: analytics-preferred
  template:
    metadata:
      labels:
        app: analytics-preferred
        tier: analytics
    spec:
      # Multiple preferred constraints with different weights
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - cpu-intensive
          - weight: 80
            preference:
              matchExpressions:
              - key: node-size
                operator: In
                values:
                - large
                - xlarge
          - weight: 60
            preference:
              matchExpressions:
              - key: network-performance
                operator: In
                values:
                - high
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - analytics-preferred
              topologyKey: kubernetes.io/hostname
          - weight: 70
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - analytics
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: analytics-engine
        image: python:3.11-slim
        command: ["python", "-c", "import time; print('Analytics running...'); time.sleep(3600)"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "800m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
