apiVersion: batch/v1
kind: Job
metadata:
  name: taint-gpu-nodes-job
spec:
  template:
    spec:
      serviceAccountName: cluster-admin
      containers:
      - name: taint-executor
        image: bitnami/kubectl:latest
        command: ["/bin/bash"]
        args: ["/scripts/taint-nodes.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: taint-gpu-nodes-script
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-admin
  namespace: voatsap
