apiVersion: v1
kind: Pod
metadata:
  name: infra-workload
  labels:
    app: infra-workload
    node-type: infrastructure
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "infra"
    effect: "NoExecute"
  nodeSelector:
    node-type: infrastructure
  containers:
  - name: monitoring-agent
    image: prom/node-exporter:latest
    ports:
    - containerPort: 9100
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  restartPolicy: Always
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: infra-logging-agent
  labels:
    app: infra-logging-agent
spec:
  selector:
    matchLabels:
      app: infra-logging-agent
  template:
    metadata:
      labels:
        app: infra-logging-agent
        node-type: infrastructure
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "infra"
        effect: "NoExecute"
      - key: "dedicated"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
      nodeSelector:
        node-type: infrastructure
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.14-1
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
