apiVersion: v1
kind: Pod
metadata:
  name: critical-workload
  labels:
    app: critical-workload
    workload: critical
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "critical"
    effect: "PreferNoSchedule"
  nodeSelector:
    workload: critical
  containers:
  - name: critical-app
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-service
  labels:
    app: critical-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: critical-service
  template:
    metadata:
      labels:
        app: critical-service
        workload: critical
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "critical"
        effect: "PreferNoSchedule"
      nodeSelector:
        workload: critical
      containers:
      - name: critical-app
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
