apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configwatchers.k8spatterns.io
spec:
  group: k8spatterns.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              configMap:
                type: string
                description: "Name of the ConfigMap to watch"
              selector:
                type: string
                description: "Label selector for pods/deployments to restart"
            required:
            - configMap
            - selector
          status:
            type: object
            properties:
              lastUpdate:
                type: string
                format: date-time
              message:
                type: string
        required:
        - spec
  scope: Namespaced
  names:
    plural: configwatchers
    singular: configwatcher
    kind: ConfigWatcher
    shortNames:
    - cw
