apiVersion: v1
kind: Pod
metadata:
  name: crashloop-example
  labels:
    app: crashloop-demo
spec:
  containers:
  - name: failing-app
    image: busybox
    command: ["sh", "-c"]
    args: ["echo 'Starting app...'; sleep 5; echo 'App crashed!'; exit 1"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
