apiVersion: v1
kind: Pod
metadata:
  name: hostport-example
  labels:
    app: hostport-demo
spec:
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 8080  # This will cause scheduling issues if multiple pods use same hostPort
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Always
