apiVersion: v1
kind: Pod
metadata:
  name: init-container-failing
  labels:
    app: init-demo
spec:
  initContainers:
  - name: init-setup
    image: busybox
    command: ["sh", "-c"]
    args: ["echo 'Setting up...'; sleep 3; echo 'Setup complete'"]
  - name: init-failing
    image: busybox
    command: ["sh", "-c"]
    args: ["echo 'This will fail'; exit 1"]
  containers:
  - name: main-app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Always
