apiVersion: v1
kind: Pod
metadata:
  name: pending-example
  labels:
    app: pending-demo
spec:
  containers:
  - name: resource-hungry
    image: nginx
    resources:
      requests:
        memory: "16Gi"  # Requesting more memory than available on nodes
        cpu: "8"        # Requesting more CPU than available
      limits:
        memory: "32Gi"
        cpu: "16"
  restartPolicy: Always
