apiVersion: v1
kind: Service
metadata:
  name: service-no-endpoints
  labels:
    app: service-debug
spec:
  selector:
    app: wrong-label  # This selector won't match any pods
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: service-debug
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app  # Different label than service selector
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
