apiVersion: v1
kind: Pod
metadata:
  name: terminating-example
  labels:
    app: terminating-demo
  finalizers:
    - example.com/my-finalizer
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Always
